// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Test1Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        //driver = new FirefoxDriver();
        //driver = new InternetExplorerDriver();
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void test1()
    {
        driver.Navigate().GoToUrl("https://rapo-crp.sandbox.operations.dynamics.com/?cmp=DAT&mi=DefaultDashboard");
        driver.FindElement(By.Id("i0116")).SendKeys("tong.lianfang@cn.ricoh.com");
        try
        {
            Thread.Sleep(3000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.Id("idSIButton9")).Click();
        try
        {
            Thread.Sleep(3000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.CssSelector(".idp:nth-child(3)")).Click();
        try
        {
            Thread.Sleep(3000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.Id("passwordInput")).SendKeys("lucysdk@1234");
        try
        {
            Thread.Sleep(3000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.Id("submitButton")).Click();
        try
        {
            Thread.Sleep(3000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.Id("idBtn_Back")).Click();
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.Id("defaultdashboard_1_HcmRecruitmentWorkspace_text")).Click();
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.Id("HcmRecruitmentWorkspace_2_NewRecrutingProject")).Click();
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.Id("HRMRecruitingTable_4_RecruitmentProjectDetails_hrmRecruitingId_input")).SendKeys("AAA");
        driver.FindElement(By.Id("HRMRecruitingTable_4_RecruitmentProjectDetails_description_input")).SendKeys("BBB");
        driver.FindElement(By.Id("HRMRecruitingTable_4_RecruitmentProjectDetails_Recruiter_DirPerson_FK_Name_input")).SendKeys("Tony Madigan");
        driver.FindElement(By.Id("HRMRecruitingTable_4_Organization_Department_Name_input")).SendKeys("Board Members");
        driver.FindElement(By.Id("HRMRecruitingTable_4_Organization_Job_JobId_input")).SendKeys("VP of Operations");
        driver.FindElement(By.Id("HRMRecruitingTable_4_Organization_qty_input")).SendKeys("1");
        driver.FindElement(By.Id("HRMRecruitingTable_4_Dates_RequisitionApprovalDate_input")).SendKeys("12/18/2020");
        driver.FindElement(By.Id("HRMRecruitingTable_4_WebPostingGroup_webEnabled_toggle")).Click();
    }
}
